apiVersion: v1
kind: Service
metadata:
  name: {{ include "sim-vis.fullname" . }}
  labels:
    {{- include "sim-vis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: app
      protocol: TCP
      name: app
  selector:
    {{- include "sim-vis.selectorLabels" . | nindent 4 }}
    role: api
