{{- $name := include "render-worker.fullname" . -}}


apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ include "render-worker.fullname" . }}-worker
  labels:
    {{- include "render-worker.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "render-worker.selectorLabels" . | nindent 6 }}
      role: worker
  template:
    metadata:
      annotations:
        checksum/config-map: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "render-worker.selectorLabels" . | nindent 8 }}
        role: worker
    spec:
      serviceAccountName: {{ include "render-worker.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
        imagePullPolicy:  {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
        - containerPort: 80
         # protocol: TCP
        command: ["python3", "worker.py"]
       
        env:  
        - name: SERVICE_PORT
          value: {{ .Values.service.port | quote }} 
        envFrom:
            {{- include "render-worker.envFrom" . | nindent 12 }}   
        resources:
            limits:
              nvidia.com/gpu:  1
      {{- with .Values.nodeSelector }}        
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}        
      
      





