apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "render.fullname" . }}-configmap
data:
  ENVIRONMENT: {{ .Values.environment }}
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | default "" | quote }}
  {{- end }}
