{{- $name := include "tfr-backend.fullname" . -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "tfr-backend.fullname" . }}-api
  labels:
    {{- include "tfr-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: app
      protocol: TCP
      name: http
  selector:
    {{- include "tfr-backend.selectorLabels" . | nindent 4 }}
    role: api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tfr-backend.fullname" . }}-api
  labels:
    {{- include "tfr-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tfr-backend.selectorLabels" . | nindent 6 }}
      role: api
  template:
    metadata:
      annotations:
        checksum/config-map: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tfr-backend.selectorLabels" . | nindent 8 }}
        role: api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tfr-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: firebase-volume
          secret:
            secretName: firebase-service-account
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./fittingroom", "run", "api"]
          workingDir: /app
          envFrom:
            {{- include "tfr-backend.envFrom" . | nindent 12 }}
          ports:
            - name: app
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: firebase-volume
              mountPath: "/app/firebase-service-account"
              readOnly: true
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 15
            httpGet:
              path: /health
              port: app
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 15
            httpGet:
              path: /health
              port: app
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tfr-backend.fullname" . }}-api
  labels:
    {{- include "tfr-backend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $name }}-api
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}

---

{{- if .Values.api.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tfr-backend.fullname" . }}-api
  labels:
    {{- include "tfr-backend.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tfr-backend.fullname" . }}-api
  minReplicas: {{ .Values.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.api.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.api.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.api.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.api.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.api.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}