apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tfr-backend.fullname" . }}-configmap
data:
  ENVIRONMENT: {{ .Values.environment }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_HOST: {{ .Values.database.host }}
  REDIS_URL: {{ .Values.redis.host }}
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | default "" | quote }}
  {{- end }}
