{{- $name := include "tfr-backend.fullname" . -}}
{{- $labels := include "tfr-backend.labels" . -}}

{{- range $secretName, $secretSettings := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $name }}-{{ $secretName }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ $name }}-{{ $secretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ $secretSettings.secretsManagerName }}
---
{{- end }}