apiVersion: v1
kind: Service
metadata:
  name: {{ include "garment-simulation-worker.fullname" . }}
  labels:
    {{- include "garment-simulation-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: app
      protocol: TCP
      name: app
  selector:
    {{- include "garment-simulation-worker.selectorLabels" . | nindent 4 }}
